# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 23:03
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_profile_attrs'), ('accounts', '0003_add_preference'), ('accounts', '0004_val_to_charfield'), ('accounts', '0005_profile_logon_attributes_token'), ('accounts', '0006_remove_profile_attrs')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[(None, 'Unknown'), ('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('logon_attributes_token', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-modified_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='settings', max_length=50)),
                ('key', models.SlugField()),
                ('val', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set([('user', 'group', 'key')]),
        ),
    ]
