# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 22:34
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attrs',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
    ]
