# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0006_remove_profile_attrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
