# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='val',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
