# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
