# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_val_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logon_attributes_token',
            field=models.TextField(blank=True),
        ),
    ]
