# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_logon_attributes_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='attrs',
        ),
    ]
