unit_tests:
  script:
    - /bin/bash bin/ci-unit-tests.sh

  when: on_success

  stage: test

  # Cache the virtual environment per branch.
  cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    paths:
      - venv/
