before_script:
  - virtualenv -p /usr/bin/python3 venv
  - source venv/bin/activate
  - pip install -U -r requirements.txt
  - pip install flake8
  - cp settings/ci_local.py settings/local.py

unit_tests:
  script:
    - bin/run-flake8.sh && python manage.py test

  when: on_success

  stage: test

  # Cache the virtual environment per branch.
  cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    paths:
      - venv/
