# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(help_text="User's due date while this notification is created")),
                ('email', models.EmailField(help_text="User's email while this notification is created", max_length=254)),
                ('status', models.CharField(choices=[('todo', 'Waiting'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed'), ('noemail', 'No Email')], default='todo', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='phasemetadata',
            name='button_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='phasemetadata',
            name='button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='phasemetadata',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phasemetadata',
            name='subject',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='notification',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.PhaseMetadata'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set([('user', 'phase', 'due_date')]),
        ),
    ]
