# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasemetadata',
            name='modified_by',
        ),
    ]
