# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_remove_phasemetadata_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('sending', 'sending'), ('delivered', 'delivered'), ('failed', 'failed'), ('unsubscribed', 'unsubscribed'), ('noemail', 'noemail')], default='pending', max_length=20),
        ),
    ]
